#ALIASES
alias la='ls -la'
alias sl='ls'
alias l='ls'
alias ll='ls'
alias lls='ls'
alias pr='cd /home/zaid/programming_playground/'
alias prc='cd /home/zaid/programming_playground/C_Programmes/'
alias prcp='cd /home/zaid/programming_playground/cpp_programmes'
alias prp='cd /home/zaid/programming_playground/python_programmes'
alias prwp='cd /home/zaid/programming_playground/web_dev/projects'
alias turbo='cd /home/zaid/TC/BIN/'
#alias acf='auto-cpufreq --stats'
alias cls='clear && ls'
alias glogout='gnome-session-quit --logout --no-prompt'
#alias neofetch='neofetch --source $HOME/.custom/ub3d.txt'
#alias balenaetcher='./balenaEtcher-1.14.3-x64.AppImage --no-sandbox --disable-gpu-sandbox --disable-seccomp-filter-sandbox'
alias discord='/home/zaid/Downloads/Discord/Discord'

# FUNCTIONS
function channel {
	sudo dmidecode -t 17 | awk 'BEGIN { FS=":"; OFS="\t" } /Size|Channel/ { line = (line ? line OFS : "") $2 } /^$/ { print line; line="RAM" }' | grep -iv "no"
	}
# Compile C program with an output file name
function c {
	gcc -o $1 $1.c
}

# Compile CPP program with an output file name
function cpp {
	g++ -o $1 $1.cpp
}

# Notes
function note {
	savelocn=".notes/.drafts.txt"
	echo "Date: $(date)" >> $HOME/$savelocn
	echo "$@" >> $HOME/$savelocn
	echo "" >> $HOME/$savelocn
}

# Show notes
alias shownote='cat ~/.notes/.drafts.txt'
alias editnote='nano ~/.notes/.drafts.txt'
# Diary
function diary {
    savelocn=".diary/.diary.txt"
    echo "Date: $(date '+%a-%d-%b-%Y %r')" >> $HOME/$savelocn
    echo "$@" >> $HOME/$savelocn
    echo "" >> $HOME/$savelocn
}

# Show diary
alias showdiary='cat ~/.diary/.diary.txt'

# Mirroring android screen to linux
alias mirroratl='scrcpy -K'


# Nvim
#alias nvim='$HOME/nvim-linux64/bin/nvim'

function fp  {
	savelocn="~/Pictures/fingerpaint/"
	fingerpaint --line-thickness $1 -o $2.png
}
