#
# ~/.bashrc
#

# If not running interactively, don't do anything

#PATH
export PATH="$HOME/.local/bin/:$PATH"

[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias grep='grep --color=auto'
PS1='[\u@\h \W]\$ '

if [ -f ~/.bash_aliases ]; then
	source ~/.bash_aliases
fi

eval "$(starship init bash)"

### RANDOM COLOR SCRIPT ###
# Get this script from my GitLab: gitlab.com/dwt1/shell-color-scripts
# Or install it from the Arch User Repository: shell-color-scripts
colorscript -e myarch

